title: TipCRM
description: > # this means to ignore newlines until "baseurl:"
  A Fast and Efficient CRM
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.potafish.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "https://github.com/TipCRM/TipCRM/blob/dev/web/src/main/gui/web/src/assets/logo.svg"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty
